# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 15:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20171007_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='message',
            name='ifactor',
            field=models.IntegerField(default=0),
        ),
    ]
