# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_auto_20171007_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to',
        ),
        migrations.AddField(
            model_name='message',
            name='to',
            field=models.ManyToManyField(null=True, related_name='reciever', to=settings.AUTH_USER_MODEL),
        ),
    ]
