# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20171007_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='base.UserProfile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.ManyToManyField(null=True, related_name='reciever', to='base.UserProfile'),
        ),
    ]
