# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 03:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20171007_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.ManyToManyField(null=True, related_name='reciever', to=settings.AUTH_USER_MODEL),
        ),
    ]
